version: '3.8'

services:
  # iChat UI Frontend
  ichat-ui:
    build:
      context: ./ichat-ui
      dockerfile: Dockerfile
    container_name: ichat-ui-frontend
    ports:
      - "3001:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - API_BASE_URL=http://localhost:8080
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - ichat-api

  # Main iChat API Server
  ichat-api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: ichat-api-server
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
      - MCP_SERVICE_HOST=ichat-mcp-service
      - MCP_SERVICE_PORT=8089
      - CODE_GENERATION_SERVICE_HOST=ichat-code-generation-service
      - CODE_GENERATION_SERVICE_PORT=8088
      - LLM_SERVICE_HOST=ichat-llm-service
      - LLM_SERVICE_PORT=8083
      - LLM_SERVICE_URL=http://ichat-llm-service:8083
      - LOG_LEVEL=DEBUG
    volumes:
      - ./api-server/logs:/app/logs
      - ./api-server/data:/app/data
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # OCR Document Converter Service
  ocr-service:
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    container_name: ichat-ocr-service
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8081
      - OCR_DEFAULT_LANGUAGE=en
      - OCR_USE_GPU=false
      - MAX_FILE_SIZE=10485760  # 10MB
    volumes:
      - ./ocr-service/uploads:/app/uploads
      - ./ocr-service/outputs:/app/outputs
      - ./ocr-service/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # OCR service takes longer to start
    restart: unless-stopped
    depends_on:
      - ichat-api

  # LLM Service for AI responses
  llm-service:
    build:
      context: ./llm/llm-prompt-generation
      dockerfile: Dockerfile
    container_name: ichat-llm-service
    ports:
      - "8083:8083"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8083
      - LLM_HOST=0.0.0.0
      - LLM_PORT=8083
      # Model Configuration - Change LLM_MODEL_KEY to select different models
      # Options: flan-t5-base, flan-t5-small, flan-t5-large, mistral-7b-q4, mistral-7b-q5, mistral-7b-q2
      - LLM_MODEL_KEY=mistral-7b-q4
      - LLM_USE_GPU=false
      - MODEL_CACHE_DIR=/app/cache
      - RETRIEVER_SERVICE_URL=http://ichat-retriever-service:8086
      # Context Window Configuration
      - N_CTX=4096
      - N_BATCH=512
      - LLM_MAX_NEW_TOKENS=2048
      - ENABLE_CONTINUATION=true
      - SLIDING_WINDOW_TOKENS=300
      # Streaming Configuration
      - STREAM_DELAY_MS=100
      - MIN_SIMILARITY_THRESHOLD=0.5
      - RETRIEVER_TIMEOUT=300
      - MODEL_LOAD_TIMEOUT=300
      - MAX_CONTEXT_LENGTH=4000
      - ENABLE_STREAMING=true
      - STREAM_DELAY_MS=50
      # Sliding Window Continuation Configuration
      - ENABLE_CONTINUATION=true
      - MAX_CONTINUATION_LOOPS=5
      - SLIDING_WINDOW_TOKENS=300
      - CONTINUATION_THRESHOLD=0.9
    volumes:
      - ./llm/llm-prompt-generation/logs:/app/logs
      - llm-model-cache:/app/cache  # Use named volume for persistent model cache
    networks:
      - ichat-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s  # LLM service takes longer to load model
    restart: unless-stopped
    depends_on:
      - ichat-api

  # Embedding Service for document processing
  embedding-service:
    build:
      context: ./llm/embedding-service
      dockerfile: Dockerfile
    container_name: ichat-embedding-service
    ports:
      - "8085:8085"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8085
      - OCR_SERVICE_URL=http://ichat-ocr-service:8081
      - VECTOR_DB_URL=http://ichat-vector-db:8084
      - REQUEST_TIMEOUT=300
      - OCR_TIMEOUT=300
      - VECTOR_DB_TIMEOUT=300
      - LOG_LEVEL=DEBUG
      # Token-based chunking configuration
      - CHUNK_SIZE=1024
      - CHUNK_OVERLAP=200
      - MIN_CHUNK_SIZE=100
      # Search configuration
      - DEFAULT_SEARCH_LIMIT=100
      - MIN_SIMILARITY_THRESHOLD=0.5
    volumes:
      - ./llm/embedding-service/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    depends_on:
      - ocr-service
      - ichat-vector-db

  # Vector Database Service
  ichat-vector-db:
    build:
      context: ./llm/vector-db
      dockerfile: Dockerfile
    container_name: ichat-vector-db
    ports:
      - "8084:8084"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8084
      - CHROMA_DB_PATH=/app/data/chroma
    volumes:
      - ./llm/vector-db/data:/app/data
      - ./llm/vector-db/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Retriever Service for RAG
  ichat-retriever-service:
    build:
      context: ./llm/retriever-service
      dockerfile: Dockerfile
    container_name: ichat-retriever-service
    ports:
      - "8086:8086"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8086
      - VECTOR_DB_URL=http://ichat-vector-db:8084
      - EMBEDDING_SERVICE_URL=http://ichat-embedding-service:8085
      - EMBEDDING_TIMEOUT=300
      - VECTOR_DB_TIMEOUT=300
      - LOG_LEVEL=DEBUG
      # Search Configuration
      - DEFAULT_SEARCH_LIMIT=100
      - MAX_SEARCH_LIMIT=100
      - EMBEDDING_SEARCH_LIMIT=100
      - MIN_SIMILARITY_THRESHOLD=0.5
      # Context Configuration (characters)
      - CONTEXT_WINDOW_SIZE=10000
      - MAX_CONTEXT_CHUNKS=3
      # Reranking Configuration
      - ENABLE_RERANKING=true
      - RERANKER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
      - RERANKER_BATCH_SIZE=32
      - RERANKER_MAX_WORKERS=4
      - RERANKER_TIMEOUT=30
    volumes:
      - ./llm/retriever-service/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - ichat-vector-db
      - embedding-service

  # Code Generation Service
  ichat-code-generation-service:
    build:
      context: ./code-generation-service
      dockerfile: Dockerfile
    container_name: ichat-code-generation-service
    ports:
      - "8088:8088"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8088
      - LLM_SERVICE_HOST=ichat-llm-service
      - LLM_SERVICE_PORT=8083
      - LLM_PROMPT_SERVICE_HOST=ichat-llm-service
      - LLM_PROMPT_SERVICE_PORT=8083
      - EMBEDDING_SERVICE_HOST=ichat-embedding-service
      - EMBEDDING_SERVICE_PORT=8085
      - MAX_REPO_SIZE_MB=500
      - MAX_FILE_SIZE_KB=1024
      - LOG_LEVEL=INFO
      - ANALYSIS_TIMEOUT=300
      - CODE_GENERATION_TIMEOUT=300
      - HTTP_TIMEOUT=300
      - LLM_REQUEST_TIMEOUT=300
      - RAG_SYNC_THREADS=10
      - RAG_SYNC_BATCH_SIZE=5
    volumes:
      - ./code-generation-service/logs:/app/logs
      - ./code-generation-service/temp:/app/temp
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - llm-service
      - embedding-service

  # MCP Service for Model Context Protocol integration
  ichat-mcp-service:
    build:
      context: ./mcp-service
      dockerfile: Dockerfile
    container_name: ichat-mcp-service
    ports:
      - "8089:8089"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8089
      - MAX_MCP_CONNECTIONS=10
      - MCP_CONNECTION_TIMEOUT=300
      - MCP_EXECUTION_TIMEOUT=300
      - MCP_CONFIG_STORAGE_PATH=/app/data/mcp_configs
      - MCP_TEMP_PATH=/app/temp
      - OAUTH_STATE_EXPIRY=600
      - LOG_LEVEL=INFO
    volumes:
      - ./mcp-service/logs:/app/logs
      - ./mcp-service/data:/app/data
      - ./mcp-service/temp:/app/temp
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8089/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Remote Host Syncer Job for Document Synchronization
  job-remote-host-syncer:
    build:
      context: ./jobs/remote-host-syncer
      dockerfile: Dockerfile
    container_name: job-remote-host-syncer
    ports:
      - "8091:8091"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8091
      - DOCKER_ENV=true
      - MCP_SERVICE_URL=http://ichat-mcp-service:8089
      - API_SERVER_URL=http://ichat-api-server:8080
      - EMBEDDING_SERVICE_URL=http://ichat-embedding-service:8085
      - SYNC_FREQUENCY=daily
      - SYNC_TIME=02:00
      - MAX_FILE_SIZE_MB=50
      - BATCH_SIZE=100
      - MAX_CONCURRENT_CONNECTIONS=3
      - MAX_RETRIES=3
      - RETRY_DELAY_SECONDS=5
      - LOG_LEVEL=INFO
      - SUPPORTED_EXTENSIONS=.txt,.md,.py,.js,.java,.cpp,.c,.h,.json,.xml,.yaml,.yml,.csv,.log
      - RUN_INITIAL_SYNC=false
      - AUTO_RESTART_INTERRUPTED_JOBS=false
      - HEALTH_CHECK_PORT=8091
      - DB_PATH=data/syncer.db
      - LOG_FILE=logs/remote-host-syncer.log
    volumes:
      - ./jobs/remote-host-syncer/data:/app/data
      - ./jobs/remote-host-syncer/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - ichat-mcp-service
      - ichat-api
      - embedding-service

  # GitHub Repository Syncer Job for Repository Synchronization
  job-github-repo-syncer:
    build:
      context: ./jobs/github-repo-syncer
      dockerfile: Dockerfile
    container_name: job-github-repo-syncer
    ports:
      - "8092:8092"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8092
      - DOCKER_ENV=true
      - MCP_SERVICE_URL=http://ichat-mcp-service:8089
      - API_SERVER_URL=http://ichat-api-server:8080
      - EMBEDDING_SERVICE_URL=http://ichat-embedding-service:8085
      - SYNC_FREQUENCY=daily
      - SYNC_TIME=03:00
      - MAX_FILE_SIZE_MB=10
      - BATCH_SIZE=50
      - MAX_CONCURRENT_REPOSITORIES=2
      - MAX_RETRIES=3
      - RETRY_DELAY_SECONDS=5
      - LOG_LEVEL=INFO
      - CLONE_DEPTH=1
      - REQUEST_TIMEOUT=30
      - GITHUB_API_TIMEOUT=30
      - RUN_INITIAL_SYNC=false
      - AUTO_RESTART_INTERRUPTED_JOBS=false
      - HEALTH_CHECK_PORT=8092
      - DB_PATH=data/github_syncer.db
      - LOG_FILE=logs/github-repo-syncer.log
    volumes:
      - ./jobs/github-repo-syncer/data:/app/data
      - ./jobs/github-repo-syncer/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - ichat-mcp-service
      - ichat-api
      - embedding-service

networks:
  ichat-network:
    driver: bridge
    name: ichat-network

volumes:
  api-logs:
    driver: local
  ocr-uploads:
    driver: local
  ocr-outputs:
    driver: local
  ocr-logs:
    driver: local
  llm-logs:
    driver: local
  llm-cache:
    driver: local
  embedding-logs:
    driver: local
  vector-db-data:
    driver: local
  vector-db-logs:
    driver: local
  retriever-logs:
    driver: local
  code-generation-logs:
    driver: local
  code-generation-temp:
    driver: local
  mcp-logs:
    driver: local
  mcp-data:
    driver: local
  mcp-temp:
    driver: local
  llm-model-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./llm/llm-prompt-generation/cache

