version: '3.8'

services:
  # Main iChat API Server
  ichat-api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: ichat-api-server
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
    volumes:
      - ./api-server/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # OCR Document Converter Service
  ocr-service:
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    container_name: ichat-ocr-service
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8081
      - OCR_DEFAULT_LANGUAGE=en
      - OCR_USE_GPU=false
      - MAX_FILE_SIZE=10485760  # 10MB
    volumes:
      - ./ocr-service/uploads:/app/uploads
      - ./ocr-service/outputs:/app/outputs
      - ./ocr-service/logs:/app/logs
    networks:
      - ichat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # OCR service takes longer to start
    restart: unless-stopped
    depends_on:
      - ichat-api

networks:
  ichat-network:
    driver: bridge
    name: ichat-network

volumes:
  api-logs:
    driver: local
  ocr-uploads:
    driver: local
  ocr-outputs:
    driver: local
  ocr-logs:
    driver: local
